detctHCs <- function(otuTable, taxonomyCol, sampleCols){
  require(data.table)
  # list of target genera
  hcDegraders <- c("Arthrobacter",
    "Dietzia",
    "Gordonia",
    "Microbacterium",
    "Micrococcus",
    "Mycobacterium",
    "Nocardia",
    "Nocardioides",
    "Prauserella",
    "Rhodococcus",
    "Streptomyces",
    "Terrabacter",
    "Cytophaga",
    "Flavobacterium",
    "Pedobacter",
    "Bacillus",
    "Paenibacillus",
    "Planomicrobium",
    "Kordiimonas",
    "Novosphingobium",
    "Ochrobactrum",
    "Sphingobium",
    "Sphingomonas",
    "Sphingopyxis",
    "Roseobacter_clade",
    "Roseovarius",
    "Jannaschia",
    "Silicibacter",
    "Sulfitobacter",
    "Thalassospira",
    "Tranquillimonas",
    "Tropicibacter",
    "Tropicimonas",
    "Acidovorax",
    "Alcaligenes",
    "Burkholderia",
    "Comamonas",
    "Delftia",
    "Polaromonas",
    "Ralstonia",
    "Desulfatibacillum",
    "Desulfatiferula",
    "Desulfobacterium",
    "Desulfococcus",
    "Desulfoglaeba",
    "Desulfothermus",
    "Alcanivorax",
    "Alkanindiges",
    "Cycloclasticus",
    "Oleibacter",
    "Oleiphilus",
    "Oleispira",
    "Thalassolituus",
    "Acinetobacter",
    "Alteromonas",
    "Halomonas",
    "Marinobacter",
    "Microbulbifer",
    "Neptunomonas",
    "Pseudoalteromonas",
    "Pseudomonas",
    "Shewanella",
    "Vibrio")

  # coerce x to data.table class
  ifelse(is.data.table(otuTable), otuTable, setDT(otuTable))

  # detect row indices of target genera in our OTU table
  hcDegOtus <- grep(paste(hcDegraders, collapse = "|"),
    otuTable[, taxonomyCol, with = F], ignore.case = T)

return(hcDegOtus)
}
